import AppKit
import Foundation
import Testing
@testable import Barlyn

/// Tests use a **private, named** `NSPasteboard`, never `.general`. Running the suite must not
/// read or clobber whatever the developer actually has on their clipboard.
@MainActor
private func makeService(
    limit: Int = 100,
    enabled: Bool = true
) -> (ClipboardService, NSPasteboard, InMemoryClipboardHistoryStorage) {
    let preferences = PreferenceStore(storage: InMemoryPreferenceStorage())
    preferences[PreferenceKeys.clipboardHistoryLimit] = limit
    preferences[PreferenceKeys.clipboardEnabled] = enabled

    let storage = InMemoryClipboardHistoryStorage()
    let pasteboard = NSPasteboard(name: NSPasteboard.Name("dev.barlyn.tests.\(UUID().uuidString)"))
    let service = ClipboardService(storage: storage, preferences: preferences, pasteboard: pasteboard)
    return (service, pasteboard, storage)
}

@Suite("Clipboard content")
struct ClipboardContentTests {

    @Test("Previews collapse multi-line snippets to a single line")
    func previewCollapsesNewlines() {
        let item = ClipboardItem(content: .text("line one\nline two\n\nline three"))
        #expect(!item.preview.contains("\n"))
        #expect(item.preview == "line one line two line three")
    }

    @Test("Long previews are truncated")
    func previewTruncates() {
        let item = ClipboardItem(content: .text(String(repeating: "a", count: 500)))
        #expect(item.preview.count <= 121)
        #expect(item.preview.hasSuffix("…"))
    }

    @Test("Whitespace-only entries count as empty")
    func emptyDetection() {
        #expect(ClipboardItem(content: .text("   \n\t ")).isEmpty)
        #expect(ClipboardItem(content: .text("x")).isEmpty == false)
    }

    @Test("URLs and text are distinguishable and both yield plain text")
    func contentKinds() {
        let url = ClipboardContent.url(URL(string: "https://example.com")!)
        #expect(url.plainText == "https://example.com")
        #expect(ClipboardContent.text("hello").plainText == "hello")
        #expect(url != .text("https://example.com"))
    }

    @Test("Items survive a Codable round trip")
    func codableRoundTrip() throws {
        let original = ClipboardItem(content: .url(URL(string: "https://example.com/x")!))
        let data = try JSONEncoder().encode([original])
        let decoded = try JSONDecoder().decode([ClipboardItem].self, from: data)
        #expect(decoded.first?.content == original.content)
        #expect(decoded.first?.id == original.id)
    }
}

@Suite("Clipboard privacy")
@MainActor
struct ClipboardPrivacyTests {

    @Test("Entries marked private by their source are never recorded")
    func honoursConcealedMarker() {
        let (service, pasteboard, _) = makeService()

        // Exactly what a password manager writes to opt out of clipboard managers.
        pasteboard.clearContents()
        pasteboard.setString("super-secret-password", forType: .string)
        pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))

        service.pollForTesting()

        #expect(service.items.isEmpty, "A concealed entry must never enter the history")
    }

    @Test("Transient and auto-generated markers are honoured too")
    func honoursOtherMarkers() {
        for marker in ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
            let (service, pasteboard, _) = makeService()
            pasteboard.clearContents()
            pasteboard.setString("transient", forType: .string)
            pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType(marker))

            service.pollForTesting()
            #expect(service.items.isEmpty, "\(marker) should suppress recording")
        }
    }

    @Test("Pausing stops recording, and resuming does not backfill what was missed")
    func pauseDoesNotBackfill() {
        let (service, pasteboard, _) = makeService(enabled: false)
        #expect(service.isPaused)

        pasteboard.clearContents()
        pasteboard.setString("copied while paused", forType: .string)
        service.pollForTesting()
        #expect(service.items.isEmpty)

        // Resuming adopts the current change count: the user paused for a reason, and silently
        // capturing what happened during the pause would defeat it.
        service.preferencesForTesting[PreferenceKeys.clipboardEnabled] = true
        service.applyMonitoringPreference()
        service.pollForTesting()
        #expect(service.items.isEmpty, "Resuming must not retroactively capture")
    }

    @Test("Clearing history removes everything from memory and storage")
    func clearHistory() {
        let (service, pasteboard, storage) = makeService()
        pasteboard.clearContents()
        pasteboard.setString("something", forType: .string)
        service.pollForTesting()
        #expect(service.items.count == 1)

        service.clearHistory()
        #expect(service.items.isEmpty)
        #expect(storage.load().isEmpty)
    }
}

@Suite("Clipboard history")
@MainActor
struct ClipboardHistoryTests {

    @Test("A copied string is captured")
    func capturesText() {
        let (service, pasteboard, _) = makeService()
        pasteboard.clearContents()
        pasteboard.setString("docker ps", forType: .string)
        service.pollForTesting()

        #expect(service.items.count == 1)
        #expect(service.items.first?.content == .text("docker ps"))
    }

    @Test("A copied URL is captured as a URL, not missed")
    func capturesURL() {
        let (service, pasteboard, _) = makeService()
        pasteboard.clearContents()
        pasteboard.writeObjects([URL(string: "https://github.com/example")! as NSURL])
        service.pollForTesting()

        // A URL-only pasteboard item carries no `.string` type at all, so a text-only reader
        // would silently record nothing here.
        #expect(service.items.count == 1)
        #expect(service.items.first?.content == .url(URL(string: "https://github.com/example")!))
    }

    @Test("A link copied as plain text is still recognised as a URL")
    func recognisesTextualURL() {
        let (service, pasteboard, _) = makeService()
        pasteboard.clearContents()
        pasteboard.setString("https://example.com/page", forType: .string)
        service.pollForTesting()

        #expect(service.items.first?.content == .url(URL(string: "https://example.com/page")!))
    }

    @Test("Re-copying an entry moves it to the top instead of duplicating")
    func deduplicates() {
        let (service, pasteboard, _) = makeService()
        for value in ["first", "second", "first"] {
            pasteboard.clearContents()
            pasteboard.setString(value, forType: .string)
            service.pollForTesting()
        }

        #expect(service.items.count == 2)
        #expect(service.items.first?.content == .text("first"))
    }

    @Test("Unchanged pasteboard contents are not re-recorded")
    func ignoresUnchangedPasteboard() {
        let (service, pasteboard, _) = makeService()
        pasteboard.clearContents()
        pasteboard.setString("once", forType: .string)
        service.pollForTesting()
        service.pollForTesting()
        service.pollForTesting()
        #expect(service.items.count == 1)
    }

    @Test("History is capped, dropping the oldest entries")
    func respectsLimit() {
        let (service, pasteboard, _) = makeService(limit: 3)
        for value in ["a", "b", "c", "d", "e"] {
            pasteboard.clearContents()
            pasteboard.setString(value, forType: .string)
            service.pollForTesting()
        }

        #expect(service.items.count == 3)
        #expect(service.items.map(\.content) == [.text("e"), .text("d"), .text("c")])
    }

    @Test("Lowering the limit trims immediately rather than only as new entries arrive")
    func limitAppliesRetroactively() {
        let (service, pasteboard, _) = makeService(limit: 10)
        for value in ["a", "b", "c", "d"] {
            pasteboard.clearContents()
            pasteboard.setString(value, forType: .string)
            service.pollForTesting()
        }
        #expect(service.items.count == 4)

        service.preferencesForTesting[PreferenceKeys.clipboardHistoryLimit] = 2
        service.applyHistoryLimit()
        #expect(service.items.count == 2)
    }

    @Test("Deleting removes a single entry and persists the change")
    func deleteSingle() {
        let (service, pasteboard, storage) = makeService()
        for value in ["a", "b"] {
            pasteboard.clearContents()
            pasteboard.setString(value, forType: .string)
            service.pollForTesting()
        }
        let target = try! #require(service.items.first)

        service.delete(target)
        #expect(service.items.count == 1)
        #expect(storage.load().count == 1)
    }

    @Test("Restoring an entry writes it back without re-capturing it as new")
    func restoreDoesNotDuplicate() {
        let (service, pasteboard, _) = makeService()
        for value in ["older", "newer"] {
            pasteboard.clearContents()
            pasteboard.setString(value, forType: .string)
            service.pollForTesting()
        }

        service.copy(.text("older"))
        #expect(pasteboard.string(forType: .string) == "older")

        // The write bumps changeCount; without suppression the next poll would record it again
        // and the history would churn on every paste.
        service.pollForTesting()
        #expect(service.items.count == 2)
        #expect(service.items.first?.content == .text("older"))
    }

    @Test("History survives a reopened store")
    func persistence() {
        let preferences = PreferenceStore(storage: InMemoryPreferenceStorage())
        let storage = InMemoryClipboardHistoryStorage()
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("dev.barlyn.tests.\(UUID().uuidString)"))

        let first = ClipboardService(storage: storage, preferences: preferences, pasteboard: pasteboard)
        pasteboard.clearContents()
        pasteboard.setString("persisted", forType: .string)
        first.pollForTesting()

        let reopened = ClipboardService(storage: storage, preferences: preferences, pasteboard: pasteboard)
        #expect(reopened.items.first?.content == .text("persisted"))
    }

    @Test("Search matches contents and prefers the more recent among equals")
    func search() {
        let (service, pasteboard, _) = makeService()
        for value in ["ssh admin@server", "docker ps", "ssh root@host"] {
            pasteboard.clearContents()
            pasteboard.setString(value, forType: .string)
            service.pollForTesting()
        }

        let matches = service.search("ssh")
        #expect(matches.count == 2)
        #expect(matches.first?.content == .text("ssh root@host"))
        #expect(service.search("nothing-here").isEmpty)
        #expect(service.search("").count == 3)
    }
}

@Suite("Clipboard launcher integration")
@MainActor
struct ClipboardLauncherTests {

    @Test("History entries appear as copyable launcher results")
    func providesResults() async {
        let (service, pasteboard, _) = makeService()
        pasteboard.clearContents()
        pasteboard.setString("docker ps", forType: .string)
        service.pollForTesting()

        let provider = ClipboardActionProvider(clipboard: service)
        let results = await provider.results(for: LauncherQuery("docker"))

        #expect(results.count == 1)
        #expect(results.first?.kind == .clipboard)
        #expect(results.first?.action == .copyToPasteboard("docker ps"))
    }

    @Test("A blank launcher suggests a few recent entries, not the whole history")
    func limitsUnpromptedSuggestions() async {
        let (service, pasteboard, _) = makeService()
        for value in (0..<20).map({ "entry \($0)" }) {
            pasteboard.clearContents()
            pasteboard.setString(value, forType: .string)
            service.pollForTesting()
        }

        let results = await ClipboardActionProvider(clipboard: service).results(for: LauncherQuery(""))
        #expect(results.count == 5)
        // And they must not outrank the machine's state on a blank launcher.
        #expect(results.allSatisfy { $0.relevance < 0.4 })
    }
}
