import AppKit
import OSLog
import SwiftUI

/// Watches the system pasteboard and keeps a local history.
///
/// **Monitoring is polling, because macOS provides no pasteboard-change notification.**
/// `NSPasteboard.changeCount` is the only signal, and it must be read on a timer. Measured cost
/// on the development Mac: **0.73 µs per read**, so the interval is a responsiveness decision
/// rather than an energy one — but it is still a second always-on cost alongside the menu bar,
/// so it stops entirely when the user pauses it.
///
/// **Privacy rules (§37), enforced here rather than by convention:**
/// - Clipboard contents are never logged, at any level. Only counts and states are.
/// - Entries marked with the `org.nspasteboard.*` concealed/transient markers are skipped
///   entirely, which is how password managers opt out of clipboard managers.
/// - Nothing leaves the machine; the store is a local file and there is no network path.
@MainActor
@Observable
final class ClipboardService {
    private let storage: any ClipboardHistoryStorage
    private let preferences: PreferenceStore
    private let pasteboard: NSPasteboard

    private(set) var items: [ClipboardItem] = []
    private(set) var isMonitoring = false

    private var pollingTask: Task<Void, Never>?
    private var lastSeenChangeCount: Int

    /// Markers an app sets to say "do not record this". Honouring them is the platform's
    /// established opt-out convention, and it needs no hand-maintained list of app bundle ids.
    private static let privacyMarkers: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    init(
        storage: any ClipboardHistoryStorage,
        preferences: PreferenceStore,
        pasteboard: NSPasteboard = .general
    ) {
        self.storage = storage
        self.preferences = preferences
        self.pasteboard = pasteboard
        self.lastSeenChangeCount = pasteboard.changeCount
        self.items = storage.load()
    }

    var isPaused: Bool { !preferences[PreferenceKeys.clipboardEnabled] }

    var historyLimit: Int { preferences[PreferenceKeys.clipboardHistoryLimit] }

    // MARK: - Monitoring

    func startMonitoring() {
        guard pollingTask == nil, !isPaused else { return }

        let interval = Duration.seconds(preferences[PreferenceKeys.clipboardPollInterval])
        isMonitoring = true

        pollingTask = Task { [weak self] in
            while !Task.isCancelled {
                do { try await Task.sleep(for: interval) } catch { return }
                guard let self, !Task.isCancelled else { return }
                self.pollPasteboard()
            }
        }
        AppLog.clipboard.notice("Clipboard monitoring started")
    }

    func stopMonitoring() {
        pollingTask?.cancel()
        pollingTask = nil
        isMonitoring = false
        AppLog.clipboard.notice("Clipboard monitoring stopped")
    }

    /// Applies the current pause preference. Called after the setting changes.
    func applyMonitoringPreference() {
        if isPaused {
            stopMonitoring()
        } else {
            // Adopt the current change count so resuming does not retroactively capture
            // whatever was copied while paused — the user paused for a reason.
            lastSeenChangeCount = pasteboard.changeCount
            startMonitoring()
        }
    }

    /// Test seam: drives one poll synchronously instead of waiting for the timer.
    /// Named explicitly so it is obvious in production code that nothing calls it.
    func pollForTesting() { pollPasteboard() }

    /// Test seam for adjusting preferences that the service reads.
    var preferencesForTesting: PreferenceStore { preferences }

    private func pollPasteboard() {
        let current = pasteboard.changeCount
        guard current != lastSeenChangeCount else { return }
        lastSeenChangeCount = current

        guard !isPaused else { return }

        // A password manager or similar has explicitly asked not to be recorded.
        if Self.privacyMarkers.contains(where: { pasteboard.data(forType: $0) != nil }) {
            AppLog.clipboard.info("Skipped a pasteboard entry marked private by its source")
            return
        }

        guard let content = readContent() else { return }
        record(content)
    }

    /// Reads the richest representation available.
    ///
    /// URLs are read first and separately: a URL-only pasteboard item carries **no** `.string`
    /// type at all, so a text-only reader silently misses every copied link.
    private func readContent() -> ClipboardContent? {
        if let url = (pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL])?.first,
           url.scheme != nil {
            return .url(url)
        }
        if let string = pasteboard.string(forType: .string) {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }
            // A copied link often arrives as plain text rather than a URL type.
            if let url = URL(string: trimmed), let scheme = url.scheme,
               scheme == "http" || scheme == "https",
               !trimmed.contains(" ") {
                return .url(url)
            }
            return .text(string)
        }
        return nil
    }

    private func record(_ content: ClipboardContent) {
        let item = ClipboardItem(
            content: content,
            sourceBundleIdentifier: NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        )
        guard !item.isEmpty else { return }

        // Re-copying something already in the history moves it to the top instead of creating a
        // duplicate, which is what makes a history list stay useful over a long session.
        items.removeAll { $0.content == content }
        items.insert(item, at: 0)
        trimAndPersist()
    }

    // MARK: - History management

    /// Writes an entry back to the system pasteboard.
    ///
    /// Also advances the seen change count, so restoring an entry does not immediately re-capture
    /// it as a brand-new copy and shuffle the history on every paste.
    func copy(_ content: ClipboardContent) {
        pasteboard.clearContents()
        pasteboard.setString(content.plainText, forType: .string)
        lastSeenChangeCount = pasteboard.changeCount

        // Move it to the top so the most recently used entry is where the user expects it.
        if let index = items.firstIndex(where: { $0.content == content }) {
            var item = items.remove(at: index)
            item.copiedAt = .now
            items.insert(item, at: 0)
            trimAndPersist()
        }
    }

    func copy(_ item: ClipboardItem) { copy(item.content) }

    func delete(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        trimAndPersist()
        AppLog.clipboard.notice("Deleted 1 clipboard entry")
    }

    func clearHistory() {
        let count = items.count
        items = []
        storage.deleteAll()
        AppLog.clipboard.notice("Cleared clipboard history (\(count) entries)")
    }

    /// Matches history entries against a query, most recent first among equal scores.
    func search(_ query: String) -> [ClipboardItem] {
        let normalized = query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard !normalized.isEmpty else { return items }

        return items
            .compactMap { item -> (ClipboardItem, Double)? in
                guard let score = FuzzyMatcher.score(query: normalized, candidate: item.content.plainText) else {
                    return nil
                }
                return (item, score)
            }
            .sorted { left, right in
                left.1 == right.1 ? left.0.copiedAt > right.0.copiedAt : left.1 > right.1
            }
            .map(\.0)
    }

    /// Applies a changed history limit immediately, so lowering it takes effect at once rather
    /// than only as new entries arrive.
    func applyHistoryLimit() { trimAndPersist() }

    private func trimAndPersist() {
        if items.count > historyLimit {
            items.removeLast(items.count - historyLimit)
        }
        storage.save(items)
    }
}
